pool:
  vmImage: 'win1803'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: |
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  displayName: 'install yarn'

- bash: |
    yarn install
  displayName: 'yarn install'

- bash: |
    yarn ci:test
  displayName: 'yarn ci:test'
